
package convertidor;

/**
 *
 * @author Marisol
 */
public class convertidor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(convertidor.class.getName());

    /**
     * Creates new form convertidor
     */
    public convertidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingresar la cantidad:");

        jLabel2.setText("Selecciona la moneda");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion ", "Pesos", "Dolares", "Euros", "Yenes" }));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Pesos", "Dolares", "Euros", "Yenes" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(88, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         try {//inicio del bloque para manejo de excepciones 
            //jtexfile campo de texto (obtener el texto)
            //tim() eliminar espacios en blanco
            /*String texto = jTextField1.getText().trim(); la variable texto almacenara
            el contenido del campo de texto, asegurandose que no haya espacios*/
             String texto = jTextField1.getText().trim();
             //Double.parseDouble(texto); intenta convertir la cadena de texto en numero de punto flotante
             //double cantidad = almacena el valor numerico obtenido en la variable cantidad 
            double cantidad = Double.parseDouble(texto);

            //jComboBox3.getSelectedItem(); obtine el elemento que el usuario ha seleccionado en lista despegable en moneda de origen
            //(String) para asegurar que el elemento seleccionado trata como una cadena de texto 
            //String monedaOrigen = almacena el nombre de la moneda de origen  en la variable monedaOrigen
          String monedaOrigen = (String) jComboBox3.getSelectedItem();
          String monedaDestino = (String) jComboBox2.getSelectedItem();

            //if (monedaOrigen.equals(monedaDestino)) si las dos monedas seleccionadas son la misma 
            if (monedaOrigen.equals(monedaDestino)) {
                //si son iguales muestra mensaje de error con la etiqueta jlabel12 de la interfaz
                jLabel2.setText("Selecciona monedas diferentes para convertir.");
                //detiene la ejecucuin 
                return;
            }

            double Origen = 1.0;// inicializa dos variables que se usaran para guardar los factores de conversion 
            double Destino = 1.0;
            // Tasas aproximadas a pesos mexicanos (MXN)
            //switch estructura de control que se usa para seleccionar uno de varios bloques de codigo a ejecutar
            //switch determina el factor de la conversion basandose en moneda de origen y destino 
            switch (monedaOrigen) {//inicia una estructura de control que evalua el valor de la variable moneda origen la que queremos convertir 
                //asigna su tasa de cambio fijo
                case "Pesos":
                    Origen = 1.0;
                    break;
                case "Dolares":
                    Origen = 18.7;
                    break;// = 18.7 MXN
                case "Euros":
                    Origen = 19.6;
                    break;// EUR = 19.6 MXN
                case "Yenes":
                    Origen = 0.14;
                    break;// JPY = 0.14 MXN
            }

            switch (monedaDestino) {
                case "Pesos":
                    Destino = 1.0;
                    break;
                case "Dolares":
                    Destino = 18.7;
                    break;
                case "Euros":
                    Destino = 19.6;
                    break;
                case "Yenes":
                    Destino = 0.14;
                    break;
            }

            // Convertir la cantidad al valor en pesos, luego a moneda destino
            double enPesos = cantidad * Origen;
            double resultado = enPesos / Destino;

            //jLabel3.setText muestra el resultado final en la etiqueta jlabel13
            //String.format("%.2f", resultado) para asegurar que el numero solo tenga dos decimales 
            jLabel3.setText("La conversión es: " + String.format("%.2f", resultado) + " " + monedaDestino);

            //} catch (NumberFormatException e)  manejo de errores si el usuario ingreso letras o un campo vacio 
        } catch (NumberFormatException e) {
            //jLabel2.setText("Ingresa una cantidad válida."); error muestra un mensaje al usuario 
            jLabel2.setText("Ingresa una cantidad válida.");
        }


                                           


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new convertidor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
