
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class Flappy extends javax.swing.JFrame implements KeyListener {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Flappy.class.getName());

    private Timer timer; //hilo principal
    private int x = 100, y = 100; // posición inicial
    private int velocidadY = 0; // velocidad vertical
    private int gravedad = 1; // fuerza de gravedad
    private int salto = -8; // impulso hacia arriba
    private int suelo; // límite inferior del juego

    //barras
    private int tuberiaX = 600;
    private int apertura = 130;
    private int anchoTuberia = 55;

    private Random random = new Random();

    // Imágenes del Flappy
    private ImageIcon flappyUp;
    private ImageIcon flappyMid;
    private ImageIcon baseImg;
    private ImageIcon pipeGreen;
    private ImageIcon pipeBottom;

    // Estado del juego
    private boolean juegoActivo = true;

    public Flappy() {
        initComponents();
        setSize(665, 650);

        //cargar imagenes
        baseImg = new ImageIcon(this.getClass().getResource("/recursos/base.png"));
        flappyUp = new ImageIcon(this.getClass().getResource("/recursos/bluebird-upflap.png"));
        flappyMid = new ImageIcon(this.getClass().getResource("/recursos/bluebird-midflap.png"));
        pipeGreen = new ImageIcon(getClass().getResource("/recursos/pipe-Green.png"));
        pipeBottom = new ImageIcon(getClass().getResource("/recursos/pipe-Green-down.png"));

        // Sprite inicial (Bird)
        sprite.setIcon(flappyMid);
        sprite.setBounds(sprite.getX(), sprite.getY(), flappyMid.getIconWidth(),
                flappyMid.getIconHeight());

        base.setIcon(baseImg);
        base2.setIcon(baseImg);
        base.setBounds(0, this.getHeight() - baseImg.getIconHeight(), baseImg.getIconWidth(), baseImg.getIconHeight());
        base2.setBounds(base.getWidth(), this.getHeight() - baseImg.getIconHeight(), baseImg.getIconWidth(), baseImg.getIconHeight());

        //tuberias iniciales
        tuberiaArriba.setIcon(pipeGreen);
        tuberiaAbajo.setIcon(pipeBottom);
        int alturaApertura = 100 + random.nextInt(150);

        //tuberia superior arriba invertida
        tuberiaArriba.setBounds(tuberiaX, alturaApertura - pipeGreen.getIconHeight(), anchoTuberia, pipeGreen.getIconHeight());

        //tuberia inferior abajo normal
        tuberiaAbajo.setBounds(tuberiaX, alturaApertura + apertura, anchoTuberia, pipeBottom.getIconHeight());

        tuberiaArriba.setLocation(tuberiaX, tuberiaArriba.getY());
        tuberiaAbajo.setLocation(tuberiaX, tuberiaAbajo.getY());

        //limite inferior suelo
        suelo = this.getHeight() - baseImg.getIconHeight() - flappyUp.getIconHeight(); // ajustado al tamaño de la ventana y sprite

        //timer para actualizar la posicion 
        timer = new Timer(30, new ActionListener() {
            @Override
            //mainloop
            public void actionPerformed(ActionEvent e) {
                aplicarGravedad();
                moverTuberias();
                detectarColision();
            }
        });
        timer.start();

        //keyListener
        addKeyListener(this);
        setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sprite = new javax.swing.JLabel();
        tuberiaArriba = new javax.swing.JLabel();
        base = new javax.swing.JLabel();
        base2 = new javax.swing.JLabel();
        tuberiaAbajo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(665, 650));
        getContentPane().setLayout(null);

        sprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bluebird-downflap.png"))); // NOI18N
        getContentPane().add(sprite);
        sprite.setBounds(100, 100, 50, 50);

        tuberiaArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pipe-green-down.png"))); // NOI18N
        getContentPane().add(tuberiaArriba);
        tuberiaArriba.setBounds(240, -150, 55, 320);

        base.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/base.png"))); // NOI18N
        getContentPane().add(base);
        base.setBounds(340, 330, 55, 120);

        base2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/base.png"))); // NOI18N
        getContentPane().add(base2);
        base2.setBounds(0, 340, 350, 110);

        tuberiaAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pipe-green.png"))); // NOI18N
        tuberiaAbajo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        tuberiaAbajo.setIconTextGap(2);
        tuberiaAbajo.setPreferredSize(new java.awt.Dimension(52, 120));
        getContentPane().add(tuberiaAbajo);
        tuberiaAbajo.setBounds(240, 220, 60, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    //logica de gravedad y salto
    private void aplicarGravedad() {
        velocidadY += gravedad;//cada frame gravedad aumenta la velocidad
        y += velocidadY;//nueva posicion del sprit
        
        //colisiones con el suelo y el techo
        if (y >= suelo) {
            y = suelo;
            velocidadY = 0;//detener en el suelo
        }
        if (y <= 0) {
            y = 0;
            velocidadY = 0; //detener en el techo
        }
        
        //cambiar imagen segun movimiento
        if (velocidadY < 0) {
            sprite.setIcon(flappyMid);
        }else{
            sprite.setIcon(flappyUp);
        }
        sprite.setLocation(x, y);
        System.out.println("Valor x " + x + "Valor y " + y + "suelo" + suelo);
        
    }
    
    //movimiento de tuberias 
    private void moverTuberias(){
        tuberiaX -= 5;
        
        if (tuberiaX + pipeGreen.getIconWidth() < 0){
            tuberiaX = getWidth();
            int alturaApertura = 80 + random.nextInt(150);
            tuberiaArriba.setBounds(tuberiaX, alturaApertura - pipeGreen.getIconHeight(), anchoTuberia, pipeGreen.getIconHeight());
            // Tubería inferior (abajo, normal)
            tuberiaAbajo.setBounds(tuberiaX, alturaApertura + apertura,
            anchoTuberia, pipeBottom.getIconHeight());
        }else{
            tuberiaArriba.setLocation(tuberiaX, tuberiaArriba.getY());
            tuberiaAbajo.setLocation(tuberiaX, tuberiaAbajo.getY()); 
        }
    }
    
    //colisiones 
    private void detectarColision() {
      Rectangle rPajaro = sprite.getBounds();
      Rectangle rTuberiaArriba = tuberiaArriba.getBounds();
      Rectangle rTuberiaAbajo = tuberiaAbajo.getBounds();
      
      if (rPajaro.intersects(rTuberiaArriba) || rPajaro.intersects(rTuberiaAbajo)) { 
          finDelJuego();
        }
}
    //fin del juego
    private void finDelJuego(){
        juegoActivo = false;
        JOptionPane.showMessageDialog(this, "Game over");
        timer.stop();
    }
    
    public static void main (String args[]){
        
        java.awt.EventQueue.invokeLater(() -> new Flappy().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel base;
    private javax.swing.JLabel base2;
    private javax.swing.JLabel sprite;
    private javax.swing.JLabel tuberiaAbajo;
    private javax.swing.JLabel tuberiaArriba;
    // End of variables declaration//GEN-END:variables

    //eventos de teclado
    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
       if (e.getKeyCode() == KeyEvent.VK_SPACE){
            velocidadY = salto; //aplicar impulso hacia arriba 
        } 
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
}
