/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
package VerificadorPropiedades;
package: palabra reservada que declara el paquete (carpeta/espacio de nombres) donde está la clase.
VerificadorPropiedades: nombre del paquete. Sirve para organizar clases y evitar conflictos de nombres.
import javax.swing.JOptionPane;
import: importa una clase para poder usarla sin escribir el nombre completo.
javax.swing.JOptionPane: clase que muestra cuadros de diálogo (mensajes).
*/
package VerificadorPropiedades;

import javax.swing.JOptionPane;

/**
 *
 * @author Marisol
 */
public class VerificadorPropiedades extends javax.swing.JFrame {
    
    /*
    private: acceso privado: solo puede usarse dentro de esta clase.
    static: pertenece a la clase, no a instancias; solo hay una copia compartida.
    final: constante: una vez inicializada no se reasigna (no cambia la referencia).
    java.util.logging.Logger: tipo (clase Logger). Se usa para registrar mensajes y excepciones.
    logger: nombre de la variable.
    =: operador de asignación.
    java.util.logging.Logger.getLogger(...): método estático que devuelve un Logger asociado a un nombre.
    VerificadorPropiedades.class.getName():obtiene el nombre completo de la clase ("VerificadorPropiedades") para usarlo como identificador del logger.
    */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerificadorPropiedades.class.getName());

    /**
     * Creates new form VerificadorPropiedades
     */
    public VerificadorPropiedades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Propiedades");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    jButtonActionPerformerd(java.awt.event.ActionEvent evt) es la creacion del evento en el boton "convertir"
    private: acceso local a la clase
    void: no retorna nada
    jButton1ActionPerformed: nombre del método generado para el evento del botón jButton1.
    (java.awt.event.ActionEvent evt): parámetro que contiene info del evento.
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        /*
        String: tipo de dato para texto.
        textoEntero: nombre de la variable.
        =: asignación.
        "": cadena vacía (sin caracteres).
        */
        String textoEntero="";//declarar variable de tipo string, que almacena todo el resultado jtextarea1
        /*
        try:bloque donde se colocan las instrucciones que pueden lanzar excepciones.
        */
        try{
        String numText = jTextField1.getText();
        int num = Integer.parseInt(numText);//convierte el texto a numero entero
        boolean primo=false, numPerfecto=false, par=false, positivo=false;


        // primo
        int i=1, c=0;
        while(i<=num){
            if(num % i == 0){
                c++;
            }
            i++;
        }
        if (c==2){
            primo = true;
        }

        if (num<=1){
            numPerfecto = false;
        }

        int sumaDivisores = 1;

        for (int f = 2; f * f <= num; f++) {
            if (num % f == 0) {
                sumaDivisores += f;
                if (f != num / f) {
                    sumaDivisores += num / f;
                }
            }
        }

        if (sumaDivisores == num){
            numPerfecto = true;
        }


        if(num % 2 == 0){
            par = true;
        }

        if(num>0){
            positivo = true;
        }

        //mostrar los resultados completos

        if (primo==true){
            textoEntero += "Numero Primo \n";
        } else {
            textoEntero += "Numero Compuesto \n";
        }

        if (numPerfecto == true){
            textoEntero += "Numero Perfecto \n";
        }

        if (par == true){
            textoEntero += "Numero Par \n";
        }
        else{
            textoEntero += "Numero Impar \n";
        }
        if(positivo==true){
            textoEntero += "Numero positivo \n";
        } else {
            textoEntero += "Numero negativo \n";
        }

        jTextArea1.setText(textoEntero);

        /*
        catch(NumberFormatException e): captura la excepción NumberFormatException si ocurre (ej.: parseo de texto a número falla).
        e: nombre de la variable que representa la excepción atrapada.
        */
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Error, solo numeros.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VerificadorPropiedades().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
